data:
 raw_path: ../data/raw/raw_data.csv
 trusted_path: ../data/trusted/trusted_data.csv
 train_path: ../data/train_data/train_data.csv
 test_path: ../data/test_data/test_data.csv

imagem:
  path: ../imagens/mapa_mental.png